# Copyright 2019 Allanic.me ISC License License
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
# Created by mallanic <maxime@allanic.me> at 18/08/2019

version: "2"

services:
    script:
        image: 'node'
        privileged: true
        user: 'root'
        environment:
          - FORCE_COLOR=1
          - NODE_ENV=dev
        volumes:
          - .:/opt/server:cached
          - /dev/shm:/dev/shm
        command: '/opt/server/install.sh'
        ports:
          - 8082:80
          - 32400:32400